version: '3'

services:
  line-provider-redis:
    image: redis
    container_name: line-provider-redis
    ports:
      - "6379:6379"
    networks:
      - general-network
    restart: unless-stopped

  line-provider-postgres:
     image: postgres
     container_name: line-provider-postgres
     ports:
       - "5432:5432"
     networks:
       - general-network
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: postgres
     restart: unless-stopped

  line-provider-worker:
    build:
      context: lineprovider
      dockerfile: docker/worker/Dockerfile
    depends_on:
      - line-provider-redis
      - line-provider-postgres
    networks:
      - general-network
    restart: unless-stopped
    env_file:
      - lineprovider/.env
    environment:
      FROM_DOCKER: 1
      DB_HOST: line-provider-postgres
      REDIS_BROKER_HOST: line-provider-redis

  line-provider-app:
    ports:
      - "8000:8000"
    build:
      context: lineprovider
      dockerfile: Dockerfile
    depends_on:
      - line-provider-postgres
      - line-provider-redis
    expose:
      - "8000"
    env_file:
      - lineprovider/.env
    restart: unless-stopped
    networks:
      - general-network
    environment:
      APP_PORT: "8000"
      DB_HOST: line-provider-postgres
      REDIS_BROKER_HOST: line-provider-redis

  bet-maker-postgres:
    image: postgres
    container_name: bet-maker-postgres
    ports:
      - "5433:5433"
    expose:
      - "5433"
    networks:
      - general-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped
    command: -p 5433

  bet-maker-app:
    ports:
      - "8080:8080"
    build:
      context: betmaker
      dockerfile: Dockerfile
    depends_on:
      - bet-maker-postgres
    expose:
      - "8080"
    env_file:
      - betmaker/.env
    restart: unless-stopped
    networks:
      - general-network
    environment:
      APP_PORT: "8080"
      DB_HOST: bet-maker-postgres
      DB_PORT: 5433

networks:
  general-network:
    driver: bridge
