"""initial migration

Revision ID: fda28838e420
Revises: 
Create Date: 2024-08-04 21:10:20.577154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fda28838e420'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('name', sa.Text(), nullable=False, comment='Event name'),
    sa.Column('odds', sa.Numeric(precision=10, scale=2), nullable=False, comment='Event odds'),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False, comment='Event deadline'),
    sa.Column('status', sa.Enum('OPEN', 'FIRST_TEAM_WIN', 'SECOND_TEAM_WIN', name='eventstatus'), nullable=False, comment='Event status'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('update_subscribers',
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'STOPPED', name='subscriberstatus'), nullable=False),
    sa.Column('stop_reason', sa.Enum('LATENCY', 'INVALID_RESPONSE', 'URL_NOT_FOUND', name='subscriberstopreason'), nullable=True),
    sa.Column('callback_url', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_update_subscribers_status'), 'update_subscribers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_update_subscribers_status'), table_name='update_subscribers')
    op.drop_table('update_subscribers')
    op.drop_table('events')
    # ### end Alembic commands ###
